apiVersion: skaffold/v1beta4
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}"
#  kaniko:
#    buildContext:
#      gcsBucket: jenkinsx-dev-skaffold-kaniko
#    pullSecretName: kaniko-secret
#    namespace: jx
#    image: rawlingsj/executor:dev21
#    cache:
#      repo: jenkins-x-docker-registry.jx.svc.cluster.local:5000/builder-base
#    dockerConfig:
#      secretName: jenkins-docker-cfg
#    flags:
#    - --cache-dir=/workspace
profiles:
  - name: base-images
    build:
      artifacts:
      - image: builder-base-image-yum
        context: builder-base-images
        docker:
          dockerfile: Dockerfile.yum
          buildArgs:
            FROM_IMAGE: "centos:7"
      - image: builder-base-image-ruby
        context: builder-base-images
        docker:
          dockerfile: Dockerfile.apt
          buildArgs:
            FROM_IMAGE: "ruby:2.5.1"
      - image: builder-base-image-swift
        context: builder-base-images
        docker:
          dockerfile: Dockerfile.apt
          buildArgs:
            FROM_IMAGE: "swift:4.0.3"
  - name: nodejs
    build:
      artifacts:
      - image: builder-nodejs-base
        context: builder-nodejs
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
            NODE_VERSION: "11.x"
  - name: nodejs8x
    build:
      artifacts:
      - image: builder-nodejs8x-base
        context: builder-nodejs
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
            NODE_VERSION: "8.x"
  - name: nodejs10x
    build:
      artifacts:
      - image: builder-nodejs10x-base
        context: builder-nodejs
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
            NODE_VERSION: "10.x"
  - name: gradle
    build:
      artifacts:
      - image: builder-gradle-base
        context: builder-gradle
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
            GRADLE_VERSION: "4.6"
  - name: gradle4
    build:
      artifacts:
      - image: builder-gradle4-base
        context: builder-gradle
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
            GRADLE_VERSION: "4.10.3"
  - name: gradle5
    build:
      artifacts:
      - image: builder-gradle5-base
        context: builder-gradle
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
            GRADLE_VERSION: "5.1"
  - name: dotnet
    build:
      artifacts:
      - image: builder-dotnet-base
        context: builder-dotnet
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: maven-java11
    build:
      artifacts:
      - image: builder-maven-java11-base
        context: builder-maven-java11
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: maven-nodejs
    build:
      artifacts:
      - image: builder-maven-nodejs-base
        context: builder-maven-nodejs
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-maven-java11
            FROM_VERSION: "0.1.0"
  - name: aws-cdk
    build:
      artifacts:
      - image: builder-aws-cdk-base
        context: builder-aws-cdk
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-maven-nodejs
            FROM_VERSION: "0.1.0"
  - name: dlang
    build:
      artifacts:
      - image: builder-dlang-base
        context: builder-dlang
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: rust
    build:
      artifacts:
      - image: builder-rust-base
        context: builder-rust
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: go
    build:
      artifacts:
      - image: builder-go-base
        context: builder-go
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: go-maven
    build:
      artifacts:
      - image: builder-go-maven-base
        context: builder-go-maven
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-maven-32-base
            FROM_VERSION: "0.1.0"
  - name: maven
    build:
      artifacts:
      - image: builder-maven-base
        context: builder-maven
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: maven-32
    build:
      artifacts:
      - image: builder-maven-32-base
        context: builder-maven-32
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-maven-base
            FROM_VERSION: "0.1.0"
  - name: newman
    build:
      artifacts:
      - image: builder-newman-base
        context: builder-newman
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-nodejs-base
            FROM_VERSION: "0.1.0"
  - name: python
    build:
      artifacts:
      - image: builder-python-base
        context: builder-python
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: python2
    build:
      artifacts:
      - image: builder-python2-base
        context: builder-python2
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: python37
    build:
      artifacts:
      - image: builder-python37-base
        context: builder-python37
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: scala
    build:
      artifacts:
      - image: builder-scala-base
        context: builder-scala
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: terraform
    build:
      artifacts:
      - image: builder-terraform-base
        context: builder-terraform
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-yum
            FROM_VERSION: "0.1.0"
  - name: swift
    build:
      artifacts:
      - image: builder-swift-base
        context: builder-swift
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-swift
            FROM_VERSION: "0.1.0"
  - name: ruby
    build:
      artifacts:
      - image: builder-ruby-base
        context: builder-ruby
        docker:
          dockerfile: Dockerfile
          buildArgs:
            FROM_IMAGE: jenkinsxio/builder-base-image-ruby
            FROM_VERSION: "0.1.0"
deploy:
  kubectl:
    manifests:
